### ISSUE TITLE
[Question]SDK installation 

### ISSUE THREAD

**Issue by takahiro-impara** [aristanetworks/EosSdk#18]
Hi
I want to install "sdk EosSdk-1.8.1-4.17.0F.i686.rpm" into vEOS(version:4.17.0F). After  installing the extension, I checked SDK version on CLI but it couldn't function as below.
```
>>> import eossdk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/eossdk.py", line 38, in <module>
    _eossdk = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/eossdk.py", line 34, in swig_import_helper
    _mod = imp.load_module('_eossdk', fp, pathname, description)
ImportError: /lib/libeos.so.1: undefined symbol: _ZN9AgentBase6CAgent18handleSyncResponseERKN3Tac3PtrIKN5Agent12SyncResponseEEE

``` 
And I checked about vEOS and SDK versions.
```
sdk-4.17#show extensions 
Name                                       Version/Release           Status extension
------------------------------------------ ------------------------- ------ ----
EosSdk-1.8.1-4.17.0F.i686.rpm              1.8.1/3209351.ilchicagoeo A, I      1

A: available | NA: not available | I: installed | NI: not installed | F: forced

sdk-4.17#show version 
Arista vEOS
Hardware version:    
Serial number:       
System MAC address:  0800.27e2.b2df

Software image version: 4.17.0F
Architecture:           i386
Internal build version: 4.17.0F-3304146.4170F
Internal build ID:      2ec460b8-9e7e-46ef-9884-960b5b160830

Uptime:                 30 minutes
Total memory:           1893460 kB
Free memory:            917568 kB
```

Would you tell me how can I solve it ?

Thank you !

**Comment by rmadsen** [comment]
Hi @takahiro-impara - EOS SDK 1.8.0 is actually included in EOS.swi by default—there is no longer a need to install any extensions to use the SDK!  We'll update the wiki and remove `1.8.1` from the Software Downloads page to reflect this.

**Comment by takahiro-impara** [comment]
awesome! Thank you so much!
